name: CI - Patch latest Sequoia metallib's

on:
  schedule:
  - cron: "0 */3 * * *"
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  build:
    name: CI - Patch latest metallib's
    runs-on: macos-14

    env:
      # GitHub Releases API
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      

      

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

          
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Download latest Tahoe IPSW
        run: aria2c -x 16 --file-allocation=none https://asia.oss.simplehac.top/26.1-25B5042k.zip
        id: download

      - name: Test
        run: unzip 26.1-25B5042k.zip
        id: Test

      - name: Test2
        run: aria2c -x 16 --file-allocation=none https://asia.oss.simplehac.top/Info.plist
        id: download2

      - name: Build sys_patch_dict.py
        run: python3 metallib.py --build-sys-patch 26.1-25B5042k --continuous-integration

      - name: Build Package
        run: python3 metallib.py --build-pkg 26.1-25B5042k"

      - name: Upload metal libraries to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MetallibSupportPkg.pkg
          path: ./MetallibSupportPkg-*.pkg

      - name: Upload sys_patch_dict.py to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sys_patch_dict.py
          path: sys_patch_dict.py

      - name: Create GitHub release
        if: ${{ github.ref == 'refs/heads/main'}}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            MetallibSupportPkg-*.pkg
            sys_patch_dict.py
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: 26.1-25B5042k